name: Trigger auto deployment for azb49demoapp1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/azb49demoapp1-AutoDeployTrigger-55676f3a-64b2-4e61-b6c6-bcfce9e40eb0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZB49DEMOAPP1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZB49DEMOAPP1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZB49DEMOAPP1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: azb49acr.azurecr.io
          registryUsername: ${{ secrets.AZB49DEMOAPP1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZB49DEMOAPP1_REGISTRY_PASSWORD }}
          containerAppName: azb49demoapp1
          resourceGroup: AZB49CAPP
          imageToBuild: azb49acr.azurecr.io/azb49demoapp1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


